Vagrant.configure("2") do |config|
  
  config.vm.box = "generic/alpine318"
  config.vm.box_version = "4.3.12"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "abied-chS" do |master|
    master.vm.hostname = "abied-chS"
    master.vm.network "private_network", ip: "192.168.56.110"

    master.vm.synced_folder ".", "/vagrant"

    # INSTALL_K3S_EXEC options used:
    # --tls-san:            adds additional hostname to TLS certificate
    # --node-ip:            IP address for communication with the control pane 
    # --bind-address:       IP address to bind for accepting incoming connections
    # --advertise-address:  IP address that will be advertised to other components
    # --flannel-iface eth1: isolates network traffic to eth1 interface
    master.vm.provision "shell", privileged: true, inline: <<-SHELL 
      
      apk add curl 
      
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --tls-san $(hostname) --node-ip 192.168.56.110 --bind-address 192.168.56.110 --advertise-address 192.168.56.110" sh 

      sleep 10 

      kubectl apply -f /vagrant/deployment/services.yaml
      sleep 2 

      kubectl apply -f /vagrant/deployment/app1.yaml
      sleep 2

      kubectl apply -f /vagrant/deployment/app2.yaml
      sleep 2

      kubectl apply -f /vagrant/deployment/app3.yaml
      sleep 2

      kubectl apply -f /vagrant/deployment/ingress.yaml
      sleep 2

    SHELL
  end

end
