Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/debian-12"
  config.vm.box_version = "20240822.0.1"

  config.vm.define "abied-chS" do |master|
    master.vm.hostname = "abied-chS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    master.vm.provision "shell", inline: <<-SHELL 
      mkdir -p /root/.ssh /home/vagrant/.ssh
      echo '#{File.read(File.expand_path('~/.ssh/id_rsa.pub'))}' >> /root/.ssh/authorized_keys
      echo '#{File.read(File.expand_path('~/.ssh/id_rsa.pub'))}' >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /root/.ssh/authorized_keys /home/vagrant/.ssh/authorized_keys
      chmod 700 /root/.ssh/authorized_keys /home/vagrant/.ssh/authorized_keys
    SHELL
  
    master.vm.provision "shell", path: "abied-chS.sh"

  end

  config.vm.define "abied-chSW" do |worker|
    worker.vm.hostname = "abied-chSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    worker.vm.provision "shell", inline: <<-SHELL  
      mkdir -p /root/.ssh /home/vagrant/.ssh
      echo '#{File.read(File.expand_path('~/.ssh/id_rsa.pub'))}' >> /root/.ssh/authorized_keys
      echo '#{File.read(File.expand_path('~/.ssh/id_rsa.pub'))}' >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /root/.ssh/authorized_keys /home/vagrant/.ssh/authorized_keys
      chmod 700 /root/.ssh/authorized_keys /home/vagrant/.ssh/authorized_keys
    SHELL

    worker.vm.provision "shell", path: "abied-chSW.sh", args: ["192.168.56.110"]
  end

end
