Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.box_version = "4.3.12"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1 
  end

  config.vm.define "abied-chS" do |master|
    master.vm.hostname = "abied-chS"
    master.vm.network "private_network", ip: "192.168.56.110"

    master.vm.synced_folder ".", "/vagrant"

    master.vm.provision "shell", privileged: true, inline: <<-SHELL 
      mkdir -p /home/vagrant/.ssh
      echo '#{File.read(File.expand_path('~/.ssh/id_rsa.pub'))}' >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys

      apk add curl

      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --tls-san $(hostname) --node-ip 192.168.56.110 --bind-address=192.168.56.110 --advertise-address=192.168.56.110 --flannel-iface eth1" sh 

      sleep 10 

      mkdir -p /vagrant/.token

      cp /var/lib/rancher/k3s/server/node-token /vagrant/.token
    SHELL

  end

  config.vm.define "abied-chSW" do |worker|
    worker.vm.hostname = "abied-chSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.synced_folder ".", "/vagrant"

    worker.vm.provision "shell", privileged: true, inline: <<-SHELL 
      mkdir -p /home/vagrant/.ssh
      echo '#{File.read(File.expand_path('~/.ssh/id_rsa.pub'))}' >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys

      apk add curl 

      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://192.168.56.110:6443 --token-file /vagrant/.token/node-token --node-ip=192.168.56.111 --flannel-iface eth1" sh
    SHELL

  end

end
