apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will-service
  namespace: argocd
  labels:
    name: will-service
spec:
  project: default
  source:
    repoURL: https://github.com/winstonallo/abied-ch.git
    targetRevision: HEAD
    path: config
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  info:
    - name: "will-service"
      value: "this made me lose all faith in my intelligence"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 1s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 10

